# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe '01SucessRegister' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it '01SucessRegister' do
    @driver.get('https://buggy.justtestit.org/')
    @driver.manage.resize_to(697, 720)
    @driver.find_element(:link_text, 'Register').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('casperin123654')
    @driver.find_element(:id, 'firstName').send_keys('casper')
    @driver.find_element(:id, 'lastName').send_keys('tilin')
    @driver.find_element(:id, 'password').send_keys('Banana1@')
    @driver.find_element(:id, 'confirmPassword').send_keys('Banana1@')
    @driver.find_element(:css, '.btn-default').click
    expect(@driver.find_element(:css, '.result').text).to eq('Registration is successful')
  end
end
